Validate sortcode and account number
techblue/postcode-anywhere-restclient pull request #3
Opened 2017-07-31 09:06 UTC by dishantmehta93

2017-08-01 06:33 UTC, rasarasw commented
@dheerajarora  - Done, the review. Can you please review and merge the code?

2017-08-01 06:35 UTC, rasarasw commented on src/main/java/uk/co/techblue/postcodeanywhere/resource/BankingResource.java
> +@Path("BankAccountValidation/Interactive")
@dishantmehta93  - Shouldn't we add '/' before the BankAccountValidation?

2017-08-01 06:38 UTC, rasarasw commented on src/main/java/uk/co/techblue/postcodeanywhere/resource/BankingResource.java
> +@Path("BankAccountValidation/Interactive")
@dishantmehta93  - Can you please add '/' before the BankAccountValidation?

2017-08-01 07:03 UTC, dheerajarora requested changes
I cannot see the code to test this service in test cases. Please add a test method to test BankAccountValidationService

2017-08-01 07:03 UTC, dheerajarora commented on src/main/java/uk/co/techblue/postcodeanywhere/dto/captureplus/BankingResponse.java
> +public class BankingResponse extends BaseDto {
Rename the class to BankAccountValidationResponse

2017-08-01 07:03 UTC, dheerajarora commented on src/main/java/uk/co/techblue/postcodeanywhere/service/BankingService.java
> +public class BankingService extends Service<BankingResource> {
Rename this to BankAccountValidationService

2017-08-01 07:03 UTC, dheerajarora commented on src/main/java/uk/co/techblue/postcodeanywhere/resource/BankingResource.java
> +public interface BankingResource extends Resource {
Rename this to BankAccountValidationResource

2017-08-01 07:03 UTC, dheerajarora commented on src/main/java/uk/co/techblue/postcodeanywhere/dto/captureplus/BankingValidationRecord.java
> +public class BankingValidationRecord extends BaseDto {
Rename this to BankAccountValidationRecord

2017-08-02 03:38 UTC, dheerajarora commented on src/main/java/uk/co/techblue/postcodeanywhere/resource/BankingResource.java
> +public interface BankingResource extends Resource {
it needs to be changed to BackAccountValidationResource

2017-08-02 03:38 UTC, dheerajarora approved these changes

2017-08-02 03:50 UTC, dheerajarora approved these changes

2017-08-02 03:50 UTC, merged